const sayings = [
  { autor: "C. S. Lewis", dizer: "Cada vez que você faz uma opção está transformando sua essência em alguma coisa um pouco diferente do que era antes."},
  { autor: "C. S. Lewis", dizer: "Tudo que é eterno está eternamente acima do tempo."},
  { autor: "C. S. Lewis", dizer: "Não podemos confiar em nós mesmo nem em nossos melhores momentos. Por outro lado, não devemos nos desesperar nem mesmo nos piores, pois nossos fracassos são perdoados. A única atitude fatal é se dar por satisfeito com qualquer coisa que não a perfeição."},
  { autor: "O Senhor dos Anéis", dizer: "Não devemos nos questionar porque algumas coisas nos acontecem e sim o que podemos fazer com o tempo que nos é dado."},
  { autor: "J.R.R. Tolkien", dizer: "O sofrimento é uma pedra de afiar para uma mente forte."},
  { autor: "J.R.R. Tolkien", dizer: "Não existe triunfo sem perda, não há vitória sem sofrimento, não há liberdade sem sacrifício."},
  { autor: "J.R.R. Tolkien", dizer: "Um único sonho é mais poderoso do que mil realidades"},
  { autor: "J.R.R. Tolkien", dizer: "Não se adquire um bom vocabulário com a leitura de livros escritos conforme uma ideia do que seja o vocabulário da faixa etária do leitor. Ele vem da leitura de livros acima da sua capacidade."},
  { autor: "J.R.R. Tolkien", dizer: "As aventuras não acabam nunca? Acho que não. Alguém sempre precisa continuar a história."},
  { autor: "J.R.R. Tolkien", dizer: "O elogio que vem daquele que merece o elogio está acima de todas as recompensas."},
  { autor: "J.R.R. Tolkien", dizer: "Nunca ria de dragões vivos."},
  { autor: "J.R.R. Tolkien", dizer: "Realmente, o mundo está cheio de perigos, mas ainda há muita coisa bonita, e embora atualmente o amor e a tristeza estejam misturados em todas as terras, talvez o primeiro ainda cresça com mais força."},
  { autor: "J.R.R. Tolkien", dizer: "Os atalhos causam longos atrasos."},
  { autor: "Leon Tolstói", dizer: "A verdadeira felicidade está na própria casa, entre as alegrias da família."},
  { autor: "Leon Tolstói", dizer: "Os homens distinguem-se entre si também neste caso: alguns primeiro pensam, depois falam e, em seguida, agem; outros, ao contrário, primeiro falam, depois agem e, por fim, pensam."},
  { autor: "Leon Tolstói", dizer: "A sabedoria com as coisas da vida não consiste, ao que me parece, em saber o que é preciso fazer, mas em saber o que é preciso fazer antes e o que fazer depois."},
  { autor: "Leon Tolstói", dizer: "Não é possível ser bom pela metade."},
  { autor: "Leon Tolstói", dizer: "Não alcançamos a liberdade buscando a liberdade, mas sim a verdade. A liberdade não é um fim, mas uma consequência."},
  { autor: "Leon Tolstói", dizer: "O homem não tem poder sobre nada enquanto tem medo da morte. E quem não tem medo da morte possui tudo."},
  { autor: "John Piper", dizer: "A humildade só pode sobreviver na presença de Deus."},
  { autor: "C. H. Spurgeon", dizer: "Muitos homens devem a grandeza da sua vida aos obstáculos que tiveram que vencer."},
  { autor: "", dizer: ""},
  { autor: "", dizer: ""},
  { autor: "", dizer: ""}
  ];